### ISSUE TITLE
Tests fail with "Angular could not be found on the page" error

### ISSUE THREAD

**Issue by sachams** [angular/protractor-accessibility-plugin#28]
Hi,

I downloaded master, did npm install and then npm test, but the tests fail with the error below. The webdriver server is up and running and it does load the page and produce the axe results afterwards, but the test still fails. 

Any thoughts on what i'm doing wrong?

Thanks! 

```
Failures:
1) check if accessibility plugin works on bad apps should have accessibility problems on markup
  Message:
    Failed: Angular could not be found on the page http://localhost:8081/badMarkup.html. If this is not an Angular application, you may need to turn off waiting for Angular. Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  Stack:
    Error: Angular could not be found on the page http://localhost:8081/badMarkup.html. If this is not an Angular application, you may need to turn off waiting for Angular. Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
        at /Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/protractor/built/browser.js:506:23
        at ManagedPromise.invokeCallback_ (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("should have accessibility problems on markup") in control flow
        at Object.<anonymous> (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/spec/fail_spec.js:2:3)
        at Object.<anonymous> (/Users/sms/Development/vagrant/repositories/components/protractor-accessibility-plugin/spec/fail_spec.js:1:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

1 spec, 1 failure
Finished in 10.381 seconds
```

**Comment by sachams** [comment]
Apologies, I hadn't started httpster. Doh!
